spring:
  application:
    name: usercenter
  profiles:
    active: dev  # 开发的时候写死dev就行，在服务器上运行的时候可以指定环境（dev：本地环境 || prod：生产环境 || test：测试环境）
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?refreshEnabled=true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      config:
        namespace: MAIN
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        namespace: MAIN
        group: DEFAULT_GROUP
  jackson:
    time-zone: Asia/Shanghai
  main:
    allow-bean-definition-overriding: true  # Bean 覆盖策略
