spring:
  application:
    name: usercenter
  profiles:
    active: DEV  # 开发的时候写死 DEV 就行，在服务器上运行的时候可以指定环境（DEV：本地环境 || PROD：生产环境 || TEST：测试环境）
  config:
    import:
      # 公共配置
      - optional:nacos:public-${spring.profiles.active}.yaml?refreshEnabled=true
      # 服务专属配置
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?refreshEnabled=true
  cloud:
    nacos:
      server-addr: 111.229.150.28:8848
      username: nacos
      password: nacos
      config:
        namespace: ${spring.profiles.active}
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        namespace: ${spring.profiles.active}
        group: DEFAULT_GROUP

# 日志路径配置
logback:
  path: logs/usercenter