spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        namespace: MAIN_DEV
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        refresh-enabled: true
        import-check:
          enabled: false
      discovery:
        server-addr: localhost:8848
        namespace: MAIN_DEV
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        enabled: true
